### ISSUE TITLE
Sub-sites without layout

### ISSUE THREAD

**Issue by OnkelPofanz** [bencentra/centrarium#13]
local test with centrarium-master:

- Edit _config:yml: url: "http://127.0.0.1:4000"
- Jekyll serve
- browse http://127.0.0.1:4000
--> the Startsite is ok, but a sub-site (for instance http://127.0.0.1:4000/jekyll/2015/04/18/welcome-to-jekyll.html) is without layout

What's the problem?

**Comment by bencentra** [comment]
I tried following those steps and couldn't access the site at all at http://127.0.0.1:4000. I could get to it at http://127.0.0.1:4000/centrarium/.

You shouldn't need to change the `url` field in `_config.yml` when you're developing locally with `jekyll serve`. You can keep it set to the URL you'll be deploying the site to. 

What is the value of `baseurl` in `_config.yml`?. In the demo, the default is `/centrarium/`, which means you can access the site (after running `jekyll serve`) at http://localhost:4000/centrarium/.

**Comment by OnkelPofanz** [comment]
Thank you for your answer, but no improvement. Here are some details:
- use jekyll under win7
- unzip centrarium-master
- open a commandline and change to the directory `centrarium-master`
- `bundle install`
- `jekyll serve`
- open `http:///127.0.0.1:4000` in a browser: --> Error: 'not found'
- edit `_config.yml`: change `baseurl: "/centrarium/"` to `baseurl: ""`
- restart jekyll
- reopen `http:///127.0.0.1:4000` in the browser: --> homepage is starting with correct layout
- click on a header of any post: --> the post-site starting without layout  

Where is the mistake?

**Comment by bencentra** [comment]
See if https://github.com/bencentra/centrarium/pull/15 fixes the issue for you. It makes all of the paths in the project more sane (i.e. no worrying about a preceding "/")

**Comment by OnkelPofanz** [comment]
Yes, that is the solution. **Thank you!**
I close this issue. Bye!
