### ISSUE TITLE
Potential feature additions

### ISSUE THREAD

**Issue by Huddo121** [bencentra/centrarium#19]
Hi Ben,

I've just finished converting my blog to jekyll and loved the look of your theme, so I decided to start using it! In doing so I began tinkering with the theme to better suit my needs, which resulted in me adding a number of features to my version of the theme. The summary of these features are;
- [X] Adding Reddit as a social share option
- [X] Adding previous/next post links at the bottom of each post
- [ ] Adding comment counts to the blog index
- [ ] Adding a lightbox include
- [ ]  Adding a quote include
- [ ] Updated Disqus functionality to work across multiple domains
- [ ] Disabling of google analytics when not in production

I've included the changes in my personal [github pages repo](https://github.com/Huddo121/huddo121.github.io), if you're keen on any of the above listed modifications let me know and I'd be happy to battle harden the changes and make them more configurable as required, as well as creating some proper single-feature PRs for you to peruse.

**Comment by bencentra** [comment]
I just checked out your new site and the post about the conversion. Great stuff! I'm definitely open about getting these modifications worked into the core theme. I say "yes" to all of them, with some notes:

* Adding previous/next post links at the bottom of each post - I like it, but make this configurable.
* Adding comment counts to the blog index - Very cool! I'd also make this configurable, probably separate from the Disqus integration itself.
* Adding a quote include - Yes to the idea, though I think we can come up with a better design. At the very least take what you have and fix the spacing to be more even.

Any of the includes and configurable features should be documented in the README. Feel free to just add them to a new section, I can go though and clean up the whole thing later.

Thanks in advance for your contributions!

**Comment by Huddo121** [comment]
Yeah, I'd aimed to make these configurable. Some of them may take a little bit of time to work out, such as the Disqus comment counter, as it's currently rendering where the categories (Which I don't use) originally were.

CSS (and SASS by extension) is definitely not my strong suit, so there are a few things that need neatening up in that area.
