### ISSUE TITLE
Documentation for newbies in Ruby world

### ISSUE THREAD

**Issue by ygayl** [bencentra/centrarium#2]
Hey @bencentra,

First of all thanks for your theme, looks like super nice!

I would like to know what is the procedure for a newbie to be able to use your theme.

I have first followed the official jekyll documentation to have jekyll running on my machine (Mac OS X) with a fresh website running locally:
- gem install jekyll
- jekyll new my-blog
- cd my-blog
- jekyll serve

It's running without any issue.

jekyll serve
Configuration file: /Users/gayly/Work/Perso/my-awesome-site/_config.yml
            Source: /Users/gayly/Work/Perso/my-awesome-site
       Destination: /Users/gayly/Work/Perso/my-awesome-site/_site
      Generating...
                    done.
 Auto-regeneration: enabled for '/Users/gayly/Work/Perso/my-awesome-site'
Configuration file: /Users/gayly/Work/Perso/my-awesome-site/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.

Then I've tried just downloaded your theme, unzip it and try to run it using jekyll serve and here is what I got:

jekyll serve
Configuration file: /Users/gayly/Work/Perso/Yassine-Gayl-Blog/_config.yml
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- jekyll-archives (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'

Do you have any idea where this could come from. I guess from something declared within the _config.yml file.

Since then, I assume that I wont be able to copy your config file and put it in the jekyll default generated directory.

Thanks for your help!

Yassine

**Comment by ygayl** [comment]
Okay I went through so many troubles (I had to install manually many gems, play with admin rights, ...) but I finally got it working. I read every where that developer should use bundle and rbenv and I think a central documentation about all those executable should be found somewhere. Of course not your responsability :smile: 
Anyways, I can now run it and play with your theme! Thanks a lot for it :)

**Comment by bencentra** [comment]
Glad you were able to work it out! I do have some installation details in the README, but it assumes a complete ruby and jekyll installation (which might not be a fair assumption). 

I'll leave this open and add some more detailed documentation soon!
