### ISSUE TITLE
Category description does not show

### ISSUE THREAD

**Issue by farmanp** [bencentra/centrarium#24]
I'm trying to show the description of a category in the _config.yml file and when I run the theme locally, it's fine but live doesn't show the description to my categories. 

www.github.com/farmanp/farmanp.github.io

**Comment by RobinChao** [comment]
I found the `_config.yml` 's cat name is Case Sensitive，should isequal to posts web's Category name.

example:

web's Category show `Thoughts`, then the `_config.yml` 's cat name is `Thoughts`.

then the Category description showed. tks.
