### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by austntatious** [bencentra/centrarium#27]
The pagination seems to be incorrect because it allows you to page backwards to Page2, and the page forward button allows you to go to page 1.
<img width="834" alt="screen shot 2016-05-31 at 1 41 57 pm" src="https://cloud.githubusercontent.com/assets/9490076/15689794/7f88e014-2735-11e6-8937-12a2322bdf75.png">
<img width="836" alt="screen shot 2016-05-31 at 1 41 43 pm" src="https://cloud.githubusercontent.com/assets/9490076/15689795/7f8f1f2e-2735-11e6-89d2-b63007e95183.png">

**Comment by bencentra** [comment]
Yeah, that does seem backwards. Good catch!

Pagination can be found here: https://github.com/bencentra/centrarium/blob/master/index.html#L44-L86. We probably just need to swap some markup around to put it in the right order.

You're welcome to submit a PR with the fix, or I can take care of it sometime soon.
