### ISSUE TITLE
Facebook and Twitter share not working properly

### ISSUE THREAD

**Issue by neorganic** [bencentra/centrarium#33]
So Facebook share popups with the wrong URL and 404 error. Do you have a fix for this?

Also the Twitter share  is being rendered without an embed image . Need to fix that too.

**Comment by bencentra** [comment]
Did your share URLs have a space in them somehow? This PR fixes that by encoding the URL, so you might want to try again: https://github.com/bencentra/centrarium/pull/35

Can you give an example of your social share config and maybe a screenshot of the broken Twitter embed?

**Comment by neorganic** [comment]
False positive. it was a problem with facebook. I used https://developers.facebook.com/tools/debug/  tool and after that everything started to work - i guess it needed some time . Twitter is also working now - as i recall this one was on my typing error. Thanks anyway! 👍
