### ISSUE TITLE
Disqus not working

### ISSUE THREAD

**Issue by bryanwhiting** [bencentra/centrarium#39]
Ben and All,

Thanks for the awesome Jekyll template. I love how simple and clean it is.

I signed up for Disqus yesterday and added my username to _config.yml, but I'm getting the Disqus troubleshooting error. You can see my first post [here](http://www.bryanwhiting.com/jekyll/2015/11/07/first-jekyll-blog.html). And here's the [Github markdown file for that post](https://github.com/bryanwhiting/bryanwhiting.github.io/blob/master/_posts/2016-11-07-first-jekyll-blog.md).

Here's my [_config.yml](https://github.com/bryanwhiting/bryanwhiting.github.io/blob/master/_config.yml). Is there something else I need to do to enable Disqus?

Thanks,

Bryan

**Comment by bencentra** [comment]
I think you do have to sign up to enable a Disqus widget on your site: https://disqus.com/profile/signup/intent/. If you haven't already, select "I want to install Disqus on my site" and sign up there. If it still doesn't work after that, let me know!

**Comment by bryanwhiting** [comment]
Thanks for your help! I figured it out. I was putting my Disqus username on the _config.yml rather than the shortname for the website. (I thought this since all the other social media connections in the _config.yml required just your username.) Being new to Disqus, I didn't know the difference! Perhaps we could add a brief comment in the Centrarium _config.yml, like, 

"# Disqus comments. Sign up for Disqus here: https://disqus.com/profile/signup/intent/. Register your githubusername.github.io and Disqus will provide you in return with a website shortname. Place the shortname here below."

Thanks!
