### ISSUE TITLE
Error with `bundle install`

### ISSUE THREAD

**Issue by nistara** [bencentra/centrarium#42]
I'm having an issue installing the site, specifically when I run `bundle install`. I tried installing yajl-ruby 1.2.1 and got an error as well, while installing the latest version of yawl-ruby gives no issues (except that I still can't run `bundle install`.

```
An error occurred while installing yajl-ruby (1.2.1), and Bundler cannot
continue.
Make sure that `gem install yajl-ruby -v '1.2.1'` succeeds before bundling.
```

Anything I can do about it? Thank you!

**Comment by bencentra** [comment]
I'm not sure where that gem is coming from, it's not in Gemfile.lock.

Using a fresh clone of the project, I was able to install everything just fine:

```bash
cd centrarium/
rvm install ruby-2.2.2
gem install bundler
bundle install
```
