### ISSUE TITLE
markdown format in the overview page

### ISSUE THREAD

**Issue by xiaopeng163** [bencentra/centrarium#46]
in the overview page, the contents of the post will be shown as the raw format, if there are some markdown format block, it will only show the original text, so could we add markdown highlight in the overview page?

<img width="836" alt="screen shot 2017-07-12 at 2 36 17 pm" src="https://user-images.githubusercontent.com/5743757/28104830-8075b270-670f-11e7-8c79-6a9f3192435a.png">

**Comment by bencentra** [comment]
I haven't tried it live, but you could try removing the "strip_html" filter from this code in `index.html`: https://github.com/bencentra/centrarium/blob/master/index.html#L22-L24. If you have lots of text formatting (especially headers), it may not look pretty.

**Comment by xiaopeng163** [comment]
thanks. but if I remove these lines, it will only show the title of each post.

**Comment by bencentra** [comment]
Not the whole line, just the "strip_html" filter

**Comment by xiaopeng163** [comment]
OK, tried. it has problem like this:
<img width="810" alt="screen shot 2017-07-13 at 7 16 27 am" src="https://user-images.githubusercontent.com/5743757/28143968-43987644-679b-11e7-8d73-1121ac2356aa.png">

**Comment by bencentra** [comment]
If the problem is it renders the complete HTML with line breaks and everything, that's not a problem - it's the expected behavior :) The markdown gets compiled to HTML by jekyll when assembling the index page, I don't know if there's a way to keep it.

**Comment by xiaopeng163** [comment]
ok, thanks
