### ISSUE TITLE
is there index how i can add tag, category? 

### ISSUE THREAD

**Issue by devAhn** [bencentra/centrarium#58]
im hardware engineer so not friendly to these front end web. (but it's fun!)
thanks if you could answer me.

**Comment by k4n9ks** [comment]
tag category url 404 ^^;

**Comment by devAhn** [comment]
https://github.com/bencentra/centrarium/issues/23 
this link may help you

**Comment by devAhn** [comment]
https://github.com/bencentra/centrarium/issues/23
this link may help you

2019년 2월 3일 (일) 오전 8:15, k4n9ks <notifications@github.com>님이 작성:
