### ISSUE TITLE
remove typography html

### ISSUE THREAD

**Issue by zroupas** [bencentra/centrarium#61]
Hi and what a great theme to be able to use and customize! 

I'm trying to remove Typography from navigation but cannot do that without breaking the page in github. I'm sure there is something I'm missing but it would be great if someone could help.

In a local jekyll setup i can see the _site folder but not in the repo that is uploaded and handled in github.

Thanks

**Comment by bencentra** [comment]
I just pushed some other changes to the theme. With the latest code you can either delete the page, or remove the `main_nav: true` from the page's front matter. The links in the header and footer are auto-generated and should update accordingly.

**Comment by zroupas** [comment]
Thanks for the help! Are there specific commits that i can checkout files from and add them to my repo? 
Or maybe another way that will not affect my changes i'm not aware of and sorry the inconvenience.

I can see that the main_nav changes are in

- about.md
- _includes/nav_links.html
- posts.html
- typography.html

so if i checkout those and remove main_nav:true from the typography it would  one of the solutions suggested?

Regards and thanks for taking the time to update your work for me

**Comment by zroupas** [comment]
Hi again,

For anyone that maybe stumble upon this, you need

_includes/footer.html
_includes/header.html
_includes/nav_links.html

and to add main_nav: true to about.md and posts.html.

Thanks for your time Ben and effort.
