### ISSUE TITLE
Incompatible with current version?

### ISSUE THREAD

**Issue by geotheory** [bencentra/centrarium#8]
Hey there.  Tried installing your nice-looking theme but hit this error:

	[user@system project]$ jekyll build
	Configuration file: /path/project/_config.yml
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate jekyll-archives-2.0.0, because jekyll-3.0.0.pre.beta9 conflicts with jekyll (~> 2.4) (Gem::LoadError)
		from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
		from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
		from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
		from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
		from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
		from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta9/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
		from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta9/lib/jekyll/plugin_manager.rb:27:in `each'
		from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta9/lib/jekyll/plugin_manager.rb:27:in `require_gems'
		from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta9/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
		from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta9/lib/jekyll/site.rb:98:in `setup'
		from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta9/lib/jekyll/site.rb:49:in `initialize'
		from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta9/lib/jekyll/commands/build.rb:30:in `new'
		from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta9/lib/jekyll/commands/build.rb:30:in `process'
		from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta9/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
		from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
		from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
		from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
		from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
		from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
		from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
		from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta9/bin/jekyll:17:in `<top (required)>'
		from /usr/bin/jekyll:23:in `load'
		from /usr/bin/jekyll:23:in `<main>'
	[user@system project]$

**Comment by bencentra** [comment]
Short term solution would be to try disabling jekyll-archives. Just remove this line in `_config.yml`: https://github.com/bencentra/centrarium/blob/master/_config.yml#L3

**Comment by geotheory** [comment]
That does half fix it:

	[user@system atbpi]$ jekyll build
	Configuration file: /path/atbpi/_config.yml
	       Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
	            Source: /path/atbpi
	       Destination: /path/atbpi/_site
	 Incremental build: enabled
	      Generating...
	  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
	                    File to import not found or unreadable: base. Load path: /path/atbpi/_sass on line 47
	jekyll 3.0.0.pre.beta9 | Error:  File to import not found or unreadable: base.
	Load path: /path/atbpi/_sass on line 47

**Comment by bencentra** [comment]
Sorry I haven't had time to dig deeper into this. If you haven't tried it yet, use Jekyll version 2.5.3. 

I see Jekyll 3.0.1 got released a few days ago, I'll try bumping the gem version and see what happens. Maybe something got fixed from the beta version you tried.

**Comment by geotheory** [comment]
Thanks for the tip

**Comment by bencentra** [comment]
I installed the latest stable jekyll (v3.0.1) and the required jekyll-paginate gem, then reran `jekyll serve` and it looks like the demo site built just fine.

See this branch for the changes: https://github.com/bencentra/centrarium/tree/jekyll3

**Comment by bencentra** [comment]
Jekyll 3 is out and works now, a compatible Gemfile and Gemfile.lock are in master.

**Comment by geotheory** [comment]
This problem has somehow resolved itself for me now.
